services:
  simplestudentapi:
    build:
      context: ./SimpleStudentApi
    container_name: simplestudentapi
    environment:
      ASPNETCORE_HTTP_PORTS: 8080
    ports:
      - "6001:8080"

  simplestudentfrontend:
    build:
      context: ./SimpleStudentFrontend
    container_name: simplestudentfrontend
    environment:
      ASPNETCORE_HTTP_PORTS: 8080
      ApiSettings__BaseUrl: http://simplestudentapi:8080
    ports:
      - "6011:8080"
    depends_on:
      - simplestudentapi
